'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { buildMuiTheme } from "@/app/mui-theme";
import SettingsDialog from "@/components/settings/settings-dialog";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const theme = buildMuiTheme();

    return (
        <html lang="en">
            <body
                className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }
            >
                <AppRouterCacheProvider options={ { enableCssLayer: true } }>
                    <ThemeProvider theme={ theme }>
                        <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)] [&>*]:max-w-6xl [&>*]:w-full">
                            <header className="relative">
                                <h1 className="text-center text-3xl">
                                    Bitcraft Online Effort Calculator
                                </h1>
                                <SettingsDialog buttonClassName={"absolute top-[0] right-[0]"}>
            
                                </SettingsDialog>
                            </header>
                            <main>
                                { children }
                            </main>
                            <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
                                Footer
                            </footer>
                        </div>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
